---
- name: Update and Install HestiaCP
  hosts: your_server_group
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache valid for 1 hour to avoid repeated updates

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Download HestiaCP install script
      get_url:
        url: https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
        dest: /tmp/hst-install.sh
        mode: '0755'

    - name: Install HestiaCP
      command: bash /tmp/hst-install.sh -y
      args:
        creates: /usr/local/hestia # This prevents re-running the script if HestiaCP is already installed
